from typing import Protocol


class TestHandler(Protocol):
    """Device handlers implement this lifecycle; runner guarantees cleanup."""

    def validate(self, context, definition): ...
    def setup(self, context, definition): ...
    def execute(self, context, definition): ...
    def cleanup(self, context, definition): ...
